---
#prerequestes
#1-Install java and net tools

#Update apt repo and cache
   - name : Update apt repo and cache
     apt:
       update_cache: yes
       force_apt_get : yes
       cache_valid_time : 3600

#Install Java 8
   - name: Install Java 8
     apt: 
       name: openjdk-8-jre-headless 
       state : present
   - name: Install net-tools
     apt:
       name: net-tools
       state : present

#2-Download and unpack nexus installer
   - name: Download nexus
     get_url:
       url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
       dest: /opt/
    register: output

#check if file exists or not

   - name: check if file exists or not
     stat:
       path: /opt/nexus
     register: stat_output

#unpack nexus.tar

   - name: unpack nexus.tar
     unarchive:
       src: "{{output.dest}}"
       dest: /opt/
     remote_src: yes
    when: not stat_output.stat.exists

#find nexus folder

   - name: find nexus folder
     find:
       path: /opt/
       pattern: "nexus-*"
       file_type: directory
     register: find_file

#rename nexus folder

   - name: rename nexus folder
     shell : mv {{find_file.files[0].path}} /opt/nexus
     when: not stat_output.stat.exists

